### ISSUE TITLE
Request: Use language strings in the values of the types

### ISSUE THREAD

**Issue by FrankyJust** [learningworks/moodle-block_advnotifications#18]
Would it be possible to use language strings in the values of the Types (warning, success, etc.)? In the table view all the English language strings are translatable, except this one. (PS: maybe use in that case strotolower php function to de-capitalize the first letter).

**Comment by zpottie** [comment]
Hi @FrankyJust - I can't change the values in the forms as it's used for logic, but I updated the table to use language strings now.

So if a user, for example, translates "Success" to "Sukses" (Afrikaans) then the form value would still be stored as "success" in the database, but when rendering the table - Moodle will get the translated string again - "Sukses". Hope this helps - this should be fixed since ef76516.

Thanks.
